export const ADS_TYPE = {
    SET_ADS: "SET_ADS",
    SET_SELECT_ADS: "SET_SELECT_ADS",
    SET_SEARCH_ADS: "SET_SEARCH_ADS",
    SET_COMMENT_ADS: "SET_COMMENT_ADS",
    SET_MODAL_ADS: "SET_MODAL_ADS"
}

